services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KEYSTATIC_USER: ${KEYSTATIC_USER:-}
      KEYSTATIC_PASSWORD: ${KEYSTATIC_PASSWORD:-}
      KEYSTATIC_GITHUB_CLIENT_ID: ${KEYSTATIC_GITHUB_CLIENT_ID:-}
      KEYSTATIC_GITHUB_CLIENT_SECRET: ${KEYSTATIC_GITHUB_CLIENT_SECRET:-}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
      KEYSTATIC_SECRET: ${KEYSTATIC_SECRET:-}
      RESEND_API_KEY: ${RESEND_API_KEY:-}
    restart: always
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eleahora-demo.rule=Host(`demo.jedav.link`)"
      - "traefik.http.routers.eleahora-demo.entrypoints=websecure"
      - "traefik.http.routers.eleahora-demo.tls.certresolver=letsencrypt"
      - "traefik.http.services.eleahora-demo.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true
